### ISSUE TITLE
tap-ctl create returned non-zero exit status 218

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/blktap#5]
After installing the `blktap-openvstorage-utils` package, we had problems on internal CI environments to create a blktap blockdevice on the system.

After asking @cnanakos it seems like I miss a package to build the kernel module for my kernel `4.4.0-31-generic` and I had to install another package from this url https://launchpad.net/ubuntu/+archive/primary/+files/blktap-dkms_2.0.93-0.6ubuntu1_amd64.deb.
After installing the `.deb` package I had to load the blktap kernel module via `modprobe blktap`.

**Comment by cnanakos** [comment]
@kinvaris What's the purpose of this issue?

**Comment by saelbrec** [comment]
@cnanakos,
Are the package dependencies correctly defined?
If yes, than we need to change our install scripts to also include the dkms package
